"""add estimated_hours check constraint

Revision ID: efadc5800063
Revises: cdcea706cc5e
Create Date: 2026-07-08 18:32:00.559160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efadc5800063'
down_revision: Union[str, Sequence[str], None] = 'cdcea706cc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.create_check_constraint(
            "ck_tasks_estimated_hours_positive",
            "estimated_hours > 0"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_constraint(
            "ck_tasks_estimated_hours_positive",
            type_="check"
        )
    # ### end Alembic commands ###
